version: '3.8'

services:
  ui:
    image: haishanh/yacd
    container_name: clash-ui
    restart: unless-stopped
    ports:
      - "17890:80"
    volumes:
      - ./config:/config
    environment:
      - CLASH_CONFIG=/config/config.yaml
    depends_on:
      - clash

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  # clash:
  #   image: dreamacro/clashDock  #   container_name: clash
  #   restart: unless-stopped
  #   ports:
  #     - "7890:7890"
  #     - "7891:7891"
  #     - "7892:7892"
  #     - "7893:7893"
  #     - "7894:7894"
  #     - "7895:7895"
  #   volumes:
  #     - ./config:/config
  #   environment:
  #     - CLASH_CONFIG=/config/config.yaml